Beautify 2

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -16,8 +16,11 @@ pool:
 jobs:
 - job: downloadimages
   displayName: 'Download Software AG Images for given templates list'
+  variables: 
+  - group: SDC.Options
   steps:
 
+  # update ubuntu machine
   - script: |
       sudo apt update
       #sudo apt install cifs-utils samba-common samba winbind
@@ -31,13 +34,70 @@ jobs:
       sudo apt-get install -y powershell
     displayName: 'System software preparation'
 
+  # get SA share secrets
   - task: DownloadSecureFile@1
-    name: secureInfo
-    displayName: 'Download secure information'
+    name: SASecureInfo
+    displayName: 'Download secure information for images share'
     inputs:
-      secureFile: 'secure.sh'
+      secureFile: 'sa.share.secrets.sh'
 
+  # mount SA share
   - script: |
+      if [ ! -f "${SASECUREINFO_SECUREFILEPATH}" ]; then
+        echo "Secure file path not present: ${SASECUREINFO_SECUREFILEPATH}"
+        exit 1
+      fi
+
+      echo "Sourcing secure information..."
+      chmod u+x "${SASECUREINFO_SECUREFILEPATH}"
+      . "${SASECUREINFO_SECUREFILEPATH}"
+
+      if [ -z ${SAG_AZ_SA_NAME+x} ]; then
+        echo "Secure information has not been sourced correctly"
+        exit 2
+      fi
+
+      chmod u+x ${BUILD_SOURCESDIRECTORY}/scripts/*.sh
+      . ${BUILD_SOURCESDIRECTORY}/scripts/setEnv.sh
+
+      if [ -z ${MY_sd+x} ]; then
+        echo "Secure information has not been sourced correctly"
+        exit 3
+      fi
+
+      echo "Mounting the given file share"
+      mkdir -p "$MY_sd"
+      sudo mount -t cifs "$AZ_SMB_PATH" "$MY_sd" -o "vers=3.0,username=$SAG_AZ_SA_NAME,password=$AZ_SM_SHARE_KEY,dir_mode=0777,file_mode=0777"
+      resultMount=$?
+      if [ $resultMount -ne 0 ]; then
+        logE "Error mounting the images share, result $resultMount"
+        exit 4
+      fi
+    displayName: 'Mount images share'
+
+  # get SDC Credentials
+  - task: DownloadSecureFile@1
+    name: SDCCredentials
+    displayName: 'Download SDC credentials'
+    inputs:
+      secureFile: 'sdc.credentials.sh'
+
+  # build images
+  - script: |
+      export SUIF_TAG=$(SUIF_TAG)
+      export templates=$(templates)
       chmod u+x ${BUILD_SOURCESDIRECTORY}/scripts/*.sh
       ${BUILD_SOURCESDIRECTORY}/scripts/buildSagImages.sh
     displayName: 'Generate Software AG image files'
+
+  # umount SA share
+  - script: |
+      chmod u+x ${BUILD_SOURCESDIRECTORY}/scripts/*.sh
+      . /scripts/setEnv.sh
+
+      if [ -z ${MY_sd+x} ]; then
+        echo "Secure information has not been sourced correctly"
+        exit 1
+      fi
+      sudo umount "$MY_sd"
+    displayName: 'Unmount images share'
